version: '3.8'

services: 
  mysql: 
    image: mysql:8
    environment: 
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports: 
      - '3306:3306'
    networks: 
      - mynetwork
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    environment: 
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
    